### ISSUE TITLE
Code (validation errors) in: html/tables/assessment-finished/planets-data.html

### ISSUE THREAD

**Issue by kraevit** [mdn/learning-area#100]
Hello there,

Im confused about the following code: planets-data.html wich is presented in the html tables asssesstment.
When i try to validate the code directly copied from your repository in https://validator.w3.org i got the following errors occur:

Error: A table row was 12 columns wide and exceeded the column count established using column markup (3).

I tryed to search about this topic on google, but I cant find proper solution. Another thing i noticed is, if i remove the "colgroup" tag at all the code seems to be validating fine with no errors. Why is this happening? Please help me understand it.

**Comment by chrisdavidmills** [comment]
So, the validator is complaining because the number of columns in the table is not the same as the number of columns defined in this markup:

```
      <colgroup>
        <col span="2">
        <col style="border: 2px solid black">
      </colgroup>
```

Here we have a total of three columns; a span of two and one styled with a border. If we do this, the warning goes away:

```
      <colgroup>
        <col span="2">
        <col style="border: 2px solid black">
        <col span="9">
      </colgroup>
```

I never thought to do this because it doesn't affect the functioning of the table at all; we don't want to do anything to the styling of columns 4-12! But you can do it if you are concerned about validation.

**Comment by kraevit** [comment]
Thank You,
now I see :) where the problem was. You are doing great JOB! Im feeling
better, after reading some of your work on mdn.

На пн, 1.10.2018 г. в 8:14 ч. Chris Mills <notifications@github.com> написа:

**Comment by chrisdavidmills** [comment]
@kraevit thank you for your kind words! I am so glad you are finding my articles helpful.
