### ISSUE TITLE
How about adding a module about CSS animations?

### ISSUE THREAD

**Issue by umarashfaq** [mdn/learning-area#119]
I didn't see this anything about animations in CSS guides. How about adding it there? I can create a pull request if maintainers of this repo agree with the idea.

P.S. Thank you for the wonderful work you have done. It has been very helpful.

**Comment by chrisdavidmills** [comment]
Thanks for the kind words; glad you are enjoying the learning area tutorials!

A module about CSS animations and transitions would be interested. I did think of this at some point, but in the end I didn't do it because I ran out of time. We do have some related guides in the main CSS content area, but these aren't specifically aimed at beginners. See:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transforms

**Comment by avivmu** [comment]
@chrisdavidmills close?
