### ISSUE TITLE
Overloading word "notes" in the IndexedDB example

### ISSUE THREAD

**Issue by kaycebasques** [mdn/learning-area#122]
Thanks for the IndexedDB example. Very helpful.

A minor suggestion: the [database](https://github.com/mdn/learning-area/blob/master/javascript/apis/client-side-storage/indexeddb/notes/index.js#L14) and [object store](https://github.com/mdn/learning-area/blob/master/javascript/apis/client-side-storage/indexeddb/notes/index.js#L40) are both called `notes`. In Chrome DevTools this creates a situation where you see the same word to describe different things.

![image](https://user-images.githubusercontent.com/4713486/54567141-194b6300-4990-11e9-8a26-16c8851b51b3.png)

Not sure if it's more obvious in Firefox DevTools.

For instructional purposes it might be more clear if the DB was called `notesDB` and the OS was called `notesOS`.

**Comment by chrisdavidmills** [comment]
Thanks @kaycebasques — I think you've got a good point here.

I've refiled this as https://github.com/mdn/sprints/issues/1203 so it gets picked up in our sprint triage process.

**Comment by chrisdavidmills** [comment]
@kaycebasques OK, I've made some updates. Can you give me a quick review?

I've updated the names in the articles:

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

And in the examples:

* https://github.com/mdn/learning-area/blob/master/javascript/apis/client-side-storage/indexeddb/notes/index.js
* https://github.com/mdn/learning-area/blob/master/javascript/apis/client-side-storage/indexeddb/video-store/index.js

I chose to use `x_os`/`x_db` rather than `xOS`/`xDB` as I thought beginners might be in danger of mixing them up with property/function names.

**Comment by kaycebasques** [comment]
Thanks! Looks good to me.

**Comment by chrisdavidmills** [comment]
@kaycebasques great, thanks!
