### ISSUE TITLE
The fetch() won't work on images that was saved on desktop

### ISSUE THREAD

**Issue by jasontwuk** [mdn/learning-area#155]
Hi,
I have been studying **simple-fetch.html** and **simple-fetch-chained.html** examples in JS - asynchronous - promises section. They are very good tutorial, thank you.

However, I have discovered that there is an issue with the fetch() method. When the code runs, it returns the following message in the console. (Note: I save my html and jpg files on my desktop.)

> Fetch API cannot load file:///Users/apple/Desktop/coffee.jpg. URL scheme must be "http" or "https" for CORS request.

It seems like we must use an image that is stored online, otherwise it won't work. I have tried to use fetch("https://github.com/mdn/learning-area/blob/master/javascript/asynchronous/promises/coffee.jpg") and it is blocked and failed.

My workaround is to use a pseudo image URL (eg. https://picsum.photos/200/300) from https://picsum.photos.

Just want to point this out, cheers.

**Comment by chrisdavidmills** [comment]
Hi there!

This isn't an issue or error — this is by design, to make the web secure. See here for some more information: https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

Imagine if you could load images or other files from the desktop to a web page — malicious developers could use this in all sorts of evil ways, to steal common assets like password files or other sensitive config information from a users computer.

**Comment by jasontwuk** [comment]
Thank you very much for the answer and link.
