### ISSUE TITLE
Update audio/video accessibility concerns

### ISSUE THREAD

**Issue by Malvoz** [mdn/learning-area#157]
In https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Multimedia#Accessible_audio_and_video_controls it is stated that video/audio native controls aren't keyboard accessible, which might've been true in the early ears after browsers implementing these elements. But I don't think that's the case today, the controls are keyboard accessible in Chrome, and certainly other browsers. However I'm not sure about the accessible names of the controls as I didn't use a screen reader to test it.

**Comment by chrisdavidmills** [comment]
I just did some testing, and you are right — things have got better in Chrome.

But I still mostly stand by my test in this article. You can only seem to tab to the play/pause and seek controls in Chrome, and Firefox is still bad in this respect. I have updated the text a bit to reflect Chrome's improvements.

**Comment by Malvoz** [comment]
Thanks @chrisdavidmills!

I'm surprised controls aren't keyboard accessible in e.g. Firefox, I must've been too tired to test it myself. I find that unacceptable and it makes me very concerned 👀 I'm curious to which other native elements may not be accessible in major browsers today. I might have to dig into this more and perhaps raise issues towards implementers if no such issues exist already.

**Comment by chrisdavidmills** [comment]
Yeah, it does seem strange that this kind of stuff has been neglected for so long. Form element keyboard accessibility is prety good across browsers these days, but media elements, not so much.

I guess it is because people generally roll their own media players anyway, for consistency of look and feel across browsers, which they can then make accessible. So the problem is not as pressing there. But it is still worth looking into.

**Comment by Malvoz** [comment]
FYI, there's an 11 year old bug regarding this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=494175
