### ISSUE TITLE
Solution outdated

### ISSUE THREAD

**Issue by Spixmaster** [mdn/learning-area#200]
I want to help keep the website up to date and inform you that the given solution is not correct for the given instructions above:
https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form#frame_A_payment_form

**Comment by chrisdavidmills** [comment]
Hi there @Spixmaster !

Thanks for pointing this out; I've updated the example page that is embedded on the page you are looking at so that the correct code is now used.

This change will take a while to propagate through, but rest assurated you should see the correct output example on this page soon!
