### ISSUE TITLE
<col> element does not seem to be supported anymore...

### ISSUE THREAD

**Issue by hauze-v** [mdn/learning-area#205]
After walking through the HTML Table Basics Article and learning how to style using HTML `<col>` and `colgroup>` elements I could not get my styles to show up by placing them in <col>. 

After visiting Stack Overflow it seems they're not supported and the current recommendation is to use CSS classes, however redundant that is.

Am I missing something?

**Comment by chrisdavidmills** [comment]
Hi @hauze-v !

One thing to consider here is that only a specific subset of properties are supported on `<col>`/`<colgroup>`; see https://www.w3.org/TR/CSS21/tables.html#columns.

And the thing about using CSS classes is that it is seen as best practice to set a class on `<col>` and put your styles on that class, rather than putting them directly on the `<col>` inside a `style=""` attribute. See the interactive example at the top of https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col for an example.

**Comment by hauze-v** [comment]
Understood, thanks Chris!
