### ISSUE TITLE
First Splash code not working: `guessSubmit.addEventListener('click', checkGuess);`

### ISSUE THREAD

**Issue by ndotlara** [mdn/learning-area#29]
When completing the number-guessing-game code along, I've managed to replicate the js code in the html template provided, exactly as it's directed.  I've even compared the completed html doc in the same js directory and it's a match (except for the //comments I've added).

Somehow, I still get this error: 
![screen shot 2017-08-04 at 1 43 21 am](https://user-images.githubusercontent.com/29988028/28955841-3a7e886e-78b7-11e7-8da9-dae8bdf5c31f.png)

here is the code line:
```guessSubmit.addEventListener('click', checkGuess);```

Any idea what the issue could mean?  I'm a very early-stage beginner so please bare with me!

Thank you!

**Comment by chrisdavidmills** [comment]
Hi there,

This error means that the guessSubmit variable contains a value of null, rather than the reference to a submit button input it is supposed to contain. You can't attach an event listener to a value of null, so it throws this error.

So somewhere above this line, you might not be setting the guessSubmit variable's value properly. Do you have this line in the code:

var guessSubmit = document.querySelector('.guessSubmit');

?

And in the HTML, does your submit button input have as class of guessSubmit?

<input type="submit" value="Submit guess" class="guessSubmit">

Have another look and see if you can figure this out. If you can't, I'm happy to have a look through your code to help find the error.

Best,

Chris

**Comment by ndotlara** [comment]
Thank you, Chris.  This resolved my issue. Closing.

**Comment by chrisdavidmills** [comment]
Cool, nice work!

I'm always happy to help.
