### ISSUE TITLE
This repo doesn't have the complete code of the website

### ISSUE THREAD

**Issue by ankitjain28may** [mdn/learning-area#44]
As the website has `Server-side website programming` section but this repo doesn't have its code.

**Comment by chrisdavidmills** [comment]
We decided to keep the code for the server-side tutorials in separate repos:

* https://github.com/mdn/express-locallibrary-tutorial
* https://github.com/mdn/django-locallibrary-tutorial

This is because the examples are much more complex than the client-side examples, and it makes sense to be able to download the complex example on it's own and then be able to run them right away, rather than having to mess around.

I think I'll add a section to the README to hopefully make it easier to find them.
