### ISSUE TITLE
the property  of xlink for tag tref  can not work normally in the Svg module

### ISSUE THREAD

**Issue by blkcor** [mdn/learning-area#547]
code:

```xml
<?xml version="1.0" standalone="no"?>
<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg" version="2.0">
  <text id="example" x="100" y="100">This is an example text.</text>

<text>
    <tref xlink:href="#example" />
</text>

</svg>
```

open with chrome:

This page contains the following errors:
error on line 6 at column 33: Namespace prefix xlink for href on tref is not defined

the tref seems work with error

**Comment by zfox23** [comment]
Hi @blkcor :)

In order to define the prefix `xlink`, Your `<svg />` tag code must have the following attribute:
`xmlns:xlink="http://www.w3.org/1999/xlink"`

The full, error-free code would look like this:
```svg
<?xml version="1.0" standalone="no"?>
<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="2.0">
  <text id="example" x="100" y="100">This is an example text.</text>

<text>
    <tref xlink:href="#example" />
</text>

</svg>
```

I'm closing this issue as resolved, given the above. Please let me know if you need additional assistance.
