### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/JavaScript#using_bad_browser_sniffing_code

### ISSUE THREAD

**Issue by MJWade96** [mdn/learning-area#582]
At the article  [Handling common JavaScript problems]
(https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/JavaScript#using_bad_browser_sniffing_code)
the sentence "In the bad only days when pretty much everyone used Netscape or Internet Explorer, ",
may be changed "In the bad old days"?

**Comment by hamishwillee** [comment]
Good catch. I fixed in https://github.com/mdn/content/pull/23827 .

FYI you posted this in the repo for learning area _examples_. The right place to post content issues is in the "content" repo. For things like this it is often best to simply create a fix yourself as a PR (there is a link "Edit the page on Github" at the bottom of every MDN page that takes you to the right place). Had you done so exactly as you suggested I would have very happily merged it :-)
