### ISSUE TITLE
Where are my divs?

### ISSUE THREAD

**Issue by IsmailL01** [mdn/learning-area#722]
i can't my other 4 divs they aren't be displayed ? 
look at all the screenshots then you'll see all the mistakes
https://github.com/mdn/learning-area/assets/137815026/20366917-a067-404b-99c2-3bd532ea6d1f
https://github.com/mdn/learning-area/assets/137815026/76e34fdf-c14e-4ae7-92f0-6fd5db84eca9
https://github.com/mdn/learning-area/assets/137815026/d4aa7326-526f-452b-b434-08a16aa3ca92

**Comment by bsmth** [comment]
I don't follow the question, could you provide some more details? What is the page you're coming from and the example you're referring to? Thanks a lot!

**Comment by IsmailL01** [comment]
I just created four divs in html code area then l thought l'd see those divs in html The divs were in code but l couldn't see them in html

**Comment by IsmailL01** [comment]
Sory for my bad English

**Comment by bsmth** [comment]
No problem. I'm not sure, but the examples look like they're working as expected. You can try this out: https://codepen.io/bsmth/pen/qBwmZZe

A hint for you when you're trying to get help with code, try to copy and paste the example directly like this:

```html
<div>
  <div>h</div>
  <div>e</div>
  <div>y</div>
</div>
```

It's hard to see from screenshots alone what the problem is - and you can't copy-paste the code either so someone can try it for themselves. I can recommend codepen because you can share links like the one above, and the [MDN playground](https://developer.mozilla.org/en-US/play).

I'm going to close this one, but these resources might be useful for you:

* The new Curriculum: https://developer.mozilla.org/en-US/curriculum/ for guided learning
* [Stack Overflow](https://stackoverflow.com/questions/) for questions about coding

I hope that helps and good luck! Thanks :)
