### ISSUE TITLE
Weird results

### ISSUE THREAD

**Issue by Kingwindie** [mdn/learning-area#73]
>`var dogs = ["Thunder" , "Billy" , "Jonter" , "Lomber" , "Steward"];`
>`var info = "The names of my dogs are: ";`
>`var i =0;`
>`while(i < dogs.length){`
>`if(i === dogs.length -1){`
>`console.log(info += " and " + dogs[i] + ".");`
>`}`
>`else{`
>`console.log(info += dogs[i] + ",");`
>`}`
>`i++;`
>}

Above  is the code i have and for some reason it does not print 

> The names of my dogs are: Thunder,Billy etc

instead it prints in this format

> The names of my dogs are Thunder,
> The names of my dogs are Thunder,Billy,
> The names of my dogs are Thunder,Billy,Jonter,
> The names of my dogs are Thunder,Billy,Jonter,Lomber,
> The names of my dogs are Thunder,Billy,Jonter,Lomber and Steward.

i don't see what i have done wrong,maybe someone can help me,i'm not finding help anywhere else
link to the lesson :https://github.com/mdn/learning-area/blob/master/javascript/building-blocks/loops/while.html

**Comment by chrisdavidmills** [comment]
Hi there!

So, the problem here is that you are printing the current value of `info` to the console on every iteration of the loop. What you need to do is just concatenate the new substrings on to the end of `info` on each loop iteration, and then only print `info` to the console at the end of your code, after the loop has finished iterating.

Here is a working version:

```
var dogs = ["Thunder" , "Billy" , "Jonter" , "Lomber" , "Steward"];
var info = "The names of my dogs are: ";
var i =0;
while(i < dogs.length){
if(i === dogs.length -1){
  info += "and " + dogs[i] + ".";
}
else{
  info += dogs[i] + ", ";
}
i++;
}

console.log(info);
```

Hope this helps. Feel free to ask if you have any more questions.

**Comment by Kingwindie** [comment]
Thank you.
